/** Maps bridge actions to MCP tool names for coverage checks. */
export const ACTION_MCP_MAP = {
  ping: 'edge_ping',
  listTabs: 'edge_list_tabs',
  listFrames: 'edge_list_frames',
  getAllowlist: 'edge_get_allowlist',
  setAllowlist: 'edge_set_allowlist',
  activateTab: 'edge_activate_tab',
  newTab: 'edge_new_tab',
  closeTab: 'edge_close_tab',
  reloadTab: 'edge_reload_tab',
  navigate: 'edge_navigate',
  listDownloads: 'edge_list_downloads',
  waitForDownload: 'edge_wait_for_download',
  getUrl: 'edge_get_url',
  getTitle: 'edge_get_title',
  snapshot: 'edge_snapshot',
  exists: 'edge_exists',
  query: 'edge_query',
  getAttribute: 'edge_get_attribute',
  getText: 'edge_get_text',
  getHtml: 'edge_get_html',
  click: 'edge_click',
  clickAt: 'edge_click_at',
  mouseMove: 'edge_mouse_move',
  mouseDown: 'edge_mouse_down',
  mouseUp: 'edge_mouse_up',
  wheel: 'edge_wheel',
  drag: 'edge_drag',
  fill: 'edge_fill',
  uploadFile: 'edge_upload_file',
  clear: 'edge_clear',
  focus: 'edge_focus',
  scroll: 'edge_scroll',
  hover: 'edge_hover',
  press: 'edge_press',
  doubleClick: 'edge_double_click',
  rightClick: 'edge_right_click',
  selectOption: 'edge_select_option',
  waitForSelector: 'edge_wait_for',
  waitForText: 'edge_wait_for',
  isEnabled: 'edge_is_enabled',
  getComputedStyle: 'edge_get_computed_style',
  readConsole: 'edge_read_console',
  startNetworkMonitor: 'edge_start_network_monitor',
  stopNetworkMonitor: 'edge_stop_network_monitor',
  startRecording: 'edge_start_recording',
  stopRecording: 'edge_stop_recording',
  readNetworkLog: 'edge_read_network_log',
  screenshot: 'edge_screenshot',
  getViewport: 'edge_get_viewport',
  setViewport: 'edge_set_viewport',
  readPerfProbe: 'edge_read_perf_probe',
  elementInfo: 'edge_element_info',
  batch: 'edge_batch',
};

/** Actions that accept selector OR ref (not both required). */
export const SELECTOR_OR_REF_ACTIONS = new Set([
  'click', 'fill', 'clear', 'focus', 'hover', 'doubleClick', 'rightClick',
  'getAttribute', 'elementInfo', 'query', 'selectOption', 'isEnabled', 'getComputedStyle',
]);
